from .backends import FakePackagingBackend, FFmpegPackagingBackend, PackagingBackend
from .cache import (
    PACKAGE_REPORT_FILENAME,
    PACKAGE_SIDECAR_FILENAME,
    PackageSidecarError,
    build_audiobook_package_id,
    build_package_input_hash,
    canonical_package_path,
    canonical_relative_package_path,
    load_package_sidecar,
    package_sidecar_matches,
    save_package_sidecar,
)
from .engine import PackagingEngineError, package_audiobook
from .metadata import build_book_metadata_hash, normalize_book_metadata, normalize_metadata_mapping
from .models import (
    BookMetadata,
    ChapterTimelineEntry,
    CoverArtInput,
    MasteredChapterInput,
    PackageSidecar,
    PackagingBackendResult,
    PackagingCompletionStatus,
    PackagingConfig,
    PackagingFailure,
    PackagingFailureType,
    PackagingReport,
    PackagingRequest,
    PackagingResult,
    PackagingValidationStatus,
)
from .timeline import build_chapter_timeline
from .validation import validate_backend_probe, validate_cover_art_input, validate_mastered_chapter_inputs

__all__ = [
    "BookMetadata",
    "ChapterTimelineEntry",
    "CoverArtInput",
    "FakePackagingBackend",
    "FFmpegPackagingBackend",
    "MasteredChapterInput",
    "PACKAGE_REPORT_FILENAME",
    "PACKAGE_SIDECAR_FILENAME",
    "PackageSidecar",
    "PackageSidecarError",
    "PackagingBackend",
    "PackagingBackendResult",
    "PackagingCompletionStatus",
    "PackagingConfig",
    "PackagingEngineError",
    "PackagingFailure",
    "PackagingFailureType",
    "PackagingReport",
    "PackagingRequest",
    "PackagingResult",
    "PackagingValidationStatus",
    "build_audiobook_package_id",
    "build_book_metadata_hash",
    "build_chapter_timeline",
    "build_package_input_hash",
    "canonical_package_path",
    "canonical_relative_package_path",
    "load_package_sidecar",
    "normalize_book_metadata",
    "normalize_metadata_mapping",
    "package_audiobook",
    "package_sidecar_matches",
    "save_package_sidecar",
    "validate_backend_probe",
    "validate_cover_art_input",
    "validate_mastered_chapter_inputs",
]
